### ISSUE TITLE
TGX Improvement RoadMap

### ISSUE THREAD

**Issue by shenyangHuang** [fpour/TGX#43]
**Short Term Objectives**:
- [x] add contributor guidelines
- [ ] adding node / edge feature loading support, add `tgx.Graph.edge_feat` and `tgx.Graph.node_feat`
- [ ] temporal graph motif mining and visualization, counting motifs, how they change over time
- [ ] add random walk statistics on temporal graph
- [ ] spectral properties on temporal graphs 

**Long Term Objectives** (Nice to haves):
- [ ] Support for Temporal Knowledge Graph
- [ ] Support for Temporal Heterogenous Graph
- [ ] direct visualization of the dynamic graph structure
- [ ] More efficient implementation
- [ ] community detection algorithm on temporal graph

**Important** Please read the [contribution guidelines](https://complexdata-mila.github.io/TGX/contribute/) first, feel free to reach out for any questions. 

if you would like to propose novel features, functions or help out, please reach out to [shenyang.huang@mail.mcgill.ca](shenyang.huang@mail.mcgill.ca) or contact me on TG slack.
